-   id: stylelint
    name: stylelint
    entry: stylelint
    language: node
    'files': \.(css|scss|sass)$
    args: []
    require_serial: false
    additional_dependencies: ["stylelint@3.1.2"]
    minimum_pre_commit_version: '0'
